# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diapo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('chemin', models.CharField(max_length=512, unique=True)),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Boite')),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='diapo',
            name='description',
            field=models.ManyToManyField(to='photo.MotCle'),
        ),
        migrations.AlterUniqueTogether(
            name='diapo',
            unique_together=set([('boite', 'index')]),
        ),
    ]
