# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapo',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
