# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapo',
            name='chemin',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
