# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20160224_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapo',
            name='description',
            field=models.ManyToManyField(blank=True, to='photo.MotCle'),
        ),
    ]
