# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20160224_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boite',
            name='numero',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
