# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20160226_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boite',
            old_name='numero',
            new_name='repere',
        ),
    ]
