# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20160226_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Groupe',
        ),
        migrations.RenameField(
            model_name='motcle',
            old_name='categorie',
            new_name='groupe',
        ),
    ]
